# Automatically generated by configure - do not modify

all:
SRC_PATH=/home/wpy/femu-original
TARGET_DIRS=x86_64-softmmu
GDB=/usr/bin/gdb
SUBDIRS= contrib/plugins pc-bios/optionrom
PYTHON=/home/wpy/femu-original/femu-scripts/pyvenv/bin/python3 -B
MKVENV_ENSUREGROUP=/home/wpy/femu-original/femu-scripts/pyvenv/bin/python3 -B /home/wpy/femu-original/python/scripts/mkvenv.py ensuregroup  --online
GENISOIMAGE=/usr/bin/genisoimage
MESON=/home/wpy/femu-original/femu-scripts/pyvenv/bin/meson
NINJA=/usr/bin/ninja
EXESUF=
TCG_TESTS_TARGETS= x86_64-softmmu
